pygments: true
paginate: 5

title : Michał Majcherski
tagline: Blog
author :
  name : Michał Majcherski
  email : mmajcherski@gmail.com
  github : majcher
  twitter : mmajcherski
  linkedin: mmajcherski
